name: Sync Forks
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 20 * * *'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add upstream
        run: |
          git config --global user.name 'songee2020'
          git config --global user.email 'songee.liu@gmail.com'
          # "git checkout master" is unnecessary, already here by default
          git pull --unshallow  # this option is very important, you would get
                                # complains about unrelated histories without it.
                                # (but actions/checkout@v2 can also be instructed
                                # to fetch all git depth right from the start)
          git remote add upstream https://github.com/ACL4SSR/ACL4SSR.git
      - name: Git remote
        run: |
          git remote -v
      - name: Git status
        run: |
          git status
      - name: Fetch upstream
        run: |
          git fetch upstream
      - name: Merge upstream
        run: |
          git merge --no-edit upstream/master
          git push origin master
