name: Fetch upstream forks
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 20 * * *'
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git config --global user.name 'songee2020'
          # git config --global user.email '21kixc@gmail.com'
          # "git checkout master" is unnecessary, already here by default
          git pull --unshallow  # this option is very important, you would get
                                # complains about unrelated histories without it.
                                # (but actions/checkout@v2 can also be instructed
                                # to fetch all git depth right from the start)
          git remote add upstream https://github.com/ACL4SSR/ACL4SSR.git
          git fetch upstream && git reset --hard origin/master && git clean -f -d
          # Neither forget the -b opt,
          # the feature/x ref is ambiguous at this stage
          git checkout master
          git merge --no-edit upstream/master
          git push origin master
          
          #sync tag
          git fetch upstream --tags
          git push --tags
          # etc
